### ISSUE TITLE
Close connection at exit.

### ISSUE THREAD

**Issue by mewmew** [mewspring/boxes#2]
1. Open a new game window.
2. Close the game window.
3. Open a new game window.
## Result

The port is already in use:
`OSError: [Errno 98] Address already in use`

**Comment by nlerin** [comment]
Unable to reproduce on the mighty windows!

**Comment by mewmew** [comment]
It seems to be working better now, but I was still able to reproduce this issue on Linux in the following way:
1. Start a local game.
2. Close both grid windows.
3. Host a new game.

Anyways. I'll reassign this issue as a milestone for version 0.2.

Awesome work on your last commit! :)

**Comment by mewmew** [comment]
Spring cleaning. Closing the issue for now as its been inactive for quite some time. We may simply re-open this issue next spring : )
